services:
  - type: web
    name: grassroots-boss-clean
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve@latest -s dist -l $PORT
    autoDeploy: true
